#!/usr/bin/env python3
"""Static site builder for Nishchay Photography.

Assembles the pages in src/pages/ into finished HTML at the repo root using
the shared shell in src/partials/. Standard library only - no npm, no
frameworks, no build dependencies.

    python3 build.py            # build the site
    python3 -m http.server 8000 # preview at http://localhost:8000

Each page in src/pages/ starts with a small front-matter block:

    title: Page title
    description: Meta description for search results
    output: portfolio/index.html
    ---
    <section>...</section>
"""

import html
import json
import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "src")
PAGES = os.path.join(SRC, "pages")
PARTIALS = os.path.join(SRC, "partials")

SITE_URL = "https://www.nishchayphotography.ca"

# Pages built into the sitemap, with their change priority.
SITEMAP_PRIORITY = {
    "index.html": "1.0",
    "portfolio/index.html": "0.9",
    "services/index.html": "0.9",
    "contact/index.html": "0.9",
    "about/index.html": "0.8",
    "journal/index.html": "0.7",
    "client-galleries/index.html": "0.5",
}

# Files and directories the build owns and may overwrite/remove.
GENERATED_MARKER = "<!-- Generated by build.py - edit src/ instead. -->"


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def write(path, text):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def parse_front_matter(raw):
    """Split 'key: value' lines above a --- delimiter from the page body."""
    if "\n---\n" not in raw:
        raise ValueError("page is missing its '---' front-matter delimiter")
    head, body = raw.split("\n---\n", 1)
    meta = {}
    for line in head.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip()
    return meta, body.strip()


def canonical_for(output):
    """/index.html -> /, /portfolio/index.html -> /portfolio/"""
    path = "/" + output
    if path.endswith("/index.html"):
        path = path[: -len("index.html")]
    return SITE_URL + path


def mark_active_nav(html, output):
    """Flag the nav link matching this page so CSS and screen readers agree."""
    href = canonical_for(output)[len(SITE_URL):]
    pattern = re.compile(r'(<a\s+[^>]*href="' + re.escape(href) + r'")')
    return pattern.sub(r'\1 aria-current="page"', html, count=1)


def render(template, values):
    """Replace {{token}} placeholders; unknown tokens collapse to ''."""
    def swap(match):
        return values.get(match.group(1).strip(), "")
    return re.sub(r"\{\{\s*([a-z_]+)\s*\}\}", swap, template)


def build_sitemap(outputs):
    urls = []
    for output in outputs:
        priority = SITEMAP_PRIORITY.get(output)
        if priority is None:
            continue
        urls.append(
            "  <url>\n"
            f"    <loc>{canonical_for(output)}</loc>\n"
            f"    <priority>{priority}</priority>\n"
            "  </url>"
        )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(urls)
        + "\n</urlset>\n"
    )



PACKAGES = os.path.join(ROOT, "data", "packages.json")


def esc(text):
    return html.escape(str(text), quote=False)


def format_duration(package):
    """'1-2 hours', '45 minutes', '2.5 hours' - whatever reads naturally."""
    if package.get("durationLabel"):
        return package["durationLabel"]
    lo = package["durationMinMinutes"]
    hi = package["durationMaxMinutes"]

    def one(minutes):
        if minutes < 60:
            return f"{minutes} minutes"
        hours = minutes / 60
        return f"{hours:g} hour" + ("" if hours == 1 else "s")

    if lo == hi:
        return one(hi)
    return f"{lo // 60}&ndash;{hi // 60} hours"


def format_price(package):
    price = f"${package['price']:,} CAD"
    if package.get("pricingUnit"):
        price += f" {package['pricingUnit']}"
    return price


def render_package(service, package):
    """One pricing card, matching the .package markup the stylesheet expects."""
    specs = [format_duration(package)]
    setups = package.get("setups")
    if setups and service.get("setupLabel") and not package.get("pricingUnit"):
        label = service["setupLabel"].rstrip("s")
        specs.append(f"{setups} {label}" + ("" if setups == 1 else "s"))
    specs.append(f"{package['editedImages']} edited digital images")
    if package.get("uneditedImagesRange"):
        lo, hi = package["uneditedImagesRange"]
        specs.append(f"{lo}&ndash;{hi} unedited images included")
    specs += package.get("inclusions", [])
    for note in package.get("clientResponsibilities", []):
        specs.append(note)

    featured = package.get("featured")
    classes = "package package--featured reveal" if featured else "package reveal"
    flag = '<span class="package__flag">Most booked</span>' if featured else ""
    btn = "btn btn--light btn--block" if featured else "btn btn--ghost btn--block"
    items = "\n".join(f"          <li>{esc(s)}</li>" for s in specs)

    return f"""      <article class="{classes}">
        {flag}
        <p class="eyebrow">{esc(package['name'])}</p>
        <span class="price-tag">{format_price(package)}</span>
        <ul class="spec-list">
{items}
        </ul>
        <a class="{btn}" href="/contact/?package={package['id']}">Check availability</a>
      </article>"""


def render_service(service):
    cards = "\n\n".join(render_package(service, p) for p in service["packages"])

    note = ""
    if service.get("serviceNote"):
        note = f'\n      <p class="note">{esc(service["serviceNote"])}</p>'

    band = ""
    age = service.get("ageBand")
    if age:
        band = (f'\n      <p class="note">Best photographed between '
                f'{age["minDays"]} and {age["maxDays"]} days old.</p>')

    extras = ""
    if service.get("addOns"):
        rows = "\n".join(
            f"        <li>{esc(a['name'])} &mdash; ${a['price']:,} CAD</li>"
            for a in service["addOns"])
        extras = f"""

    <div class="reveal" style="margin-top:clamp(2rem,4vw,3rem);max-width:60ch;">
      <h3>Add-ons</h3>
      <ul class="spec-list">
{rows}
      </ul>
    </div>"""

    grid = "grid grid--3" if len(service["packages"]) >= 3 else "grid grid--2"

    return f"""<section class="section" id="{service['anchor']}">
  <div class="wrap">
    <div class="reveal" style="max-width:56ch;">
      <p class="eyebrow">{esc(service['name'])}</p>
      <h2 class="display">{esc(service['blurb'])}</h2>{note}{band}
    </div>

    <div class="{grid}" style="margin-top:clamp(2.5rem,5vw,4rem);align-items:stretch;">
{cards}
    </div>{extras}
  </div>
</section>"""


def render_packages():
    with open(PACKAGES, encoding="utf-8") as fh:
        data = json.load(fh)
    sections = [render_service(s) for s in data["services"]]
    terms = "\n".join(
        f"      <li>{esc(t)}</li>" for t in data["_meta"]["commonTerms"])
    sections.append(f"""<section class="section section--paper">
  <div class="wrap wrap--narrow">
    <h2 class="display">Booking terms</h2>
    <ul class="spec-list">
{terms}
    </ul>
    <p class="note">{esc(data['_meta']['taxNote'].split('.')[0])}.</p>
  </div>
</section>""")
    return "\n\n".join(sections)


def main():
    base = read(os.path.join(PARTIALS, "base.html"))
    header = read(os.path.join(PARTIALS, "header.html"))
    footer = read(os.path.join(PARTIALS, "footer.html"))
    widgets = read(os.path.join(PARTIALS, "widgets.html"))
    lightbox = read(os.path.join(PARTIALS, "lightbox.html"))
    packages_html = render_packages()

    outputs = []
    for filename in sorted(os.listdir(PAGES)):
        if not filename.endswith(".html"):
            continue
        meta, body = parse_front_matter(read(os.path.join(PAGES, filename)))
        body = render(body, {"packages": packages_html})
        output = meta.get("output") or filename
        canonical = canonical_for(output)

        html = render(
            base,
            {
                "title": meta.get("title", "Nishchay Photography"),
                "description": meta.get("description", ""),
                "canonical": canonical,
                "og_image": SITE_URL + meta.get("og_image", "/assets/img/og-cover.svg"),
                "og_type": meta.get("og_type", "website"),
                "body_class": meta.get("body_class", ""),
                "robots": meta.get("robots", "index, follow"),
                "jsonld": meta.get("jsonld", ""),
                "header": header,
                "footer": footer,
                "widgets": widgets,
                "lightbox": lightbox,
                "content": body,
                "marker": GENERATED_MARKER,
            },
        )
        html = mark_active_nav(html, output)
        write(os.path.join(ROOT, output), html)
        outputs.append(output)
        print(f"  build  {output}")

    write(os.path.join(ROOT, "sitemap.xml"), build_sitemap(outputs))
    print("  build  sitemap.xml")
    print(f"\nBuilt {len(outputs)} pages. Preview: python3 -m http.server 8000")


if __name__ == "__main__":
    sys.exit(main())
