#!/usr/bin/env python3
"""Static site builder for Nishchay Photography.

Assembles the pages in src/pages/ into finished HTML at the repo root using
the shared shell in src/partials/. Standard library only - no npm, no
frameworks, no build dependencies.

    python3 build.py            # build the site
    python3 -m http.server 8000 # preview at http://localhost:8000

Each page in src/pages/ starts with a small front-matter block:

    title: Page title
    description: Meta description for search results
    output: portfolio/index.html
    ---
    <section>...</section>
"""

import os
import re
import shutil
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "src")
PAGES = os.path.join(SRC, "pages")
PARTIALS = os.path.join(SRC, "partials")

SITE_URL = "https://www.nishchayphotography.ca"

# Pages built into the sitemap, with their change priority.
SITEMAP_PRIORITY = {
    "index.html": "1.0",
    "portfolio/index.html": "0.9",
    "services/index.html": "0.9",
    "contact/index.html": "0.9",
    "about/index.html": "0.8",
    "journal/index.html": "0.7",
    "client-galleries/index.html": "0.5",
}

# Files and directories the build owns and may overwrite/remove.
GENERATED_MARKER = "<!-- Generated by build.py - edit src/ instead. -->"


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def write(path, text):
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def parse_front_matter(raw):
    """Split 'key: value' lines above a --- delimiter from the page body."""
    if "\n---\n" not in raw:
        raise ValueError("page is missing its '---' front-matter delimiter")
    head, body = raw.split("\n---\n", 1)
    meta = {}
    for line in head.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip()
    return meta, body.strip()


def canonical_for(output):
    """/index.html -> /, /portfolio/index.html -> /portfolio/"""
    path = "/" + output
    if path.endswith("/index.html"):
        path = path[: -len("index.html")]
    return SITE_URL + path


def mark_active_nav(html, output):
    """Flag the nav link matching this page so CSS and screen readers agree."""
    href = canonical_for(output)[len(SITE_URL):]
    pattern = re.compile(r'(<a\s+[^>]*href="' + re.escape(href) + r'")')
    return pattern.sub(r'\1 aria-current="page"', html, count=1)


def render(template, values):
    """Replace {{token}} placeholders; unknown tokens collapse to ''."""
    def swap(match):
        return values.get(match.group(1).strip(), "")
    return re.sub(r"\{\{\s*([a-z_]+)\s*\}\}", swap, template)


def build_sitemap(outputs):
    urls = []
    for output in outputs:
        priority = SITEMAP_PRIORITY.get(output)
        if priority is None:
            continue
        urls.append(
            "  <url>\n"
            f"    <loc>{canonical_for(output)}</loc>\n"
            f"    <priority>{priority}</priority>\n"
            "  </url>"
        )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        + "\n".join(urls)
        + "\n</urlset>\n"
    )


def main():
    base = read(os.path.join(PARTIALS, "base.html"))
    header = read(os.path.join(PARTIALS, "header.html"))
    footer = read(os.path.join(PARTIALS, "footer.html"))
    widgets = read(os.path.join(PARTIALS, "widgets.html"))

    outputs = []
    for filename in sorted(os.listdir(PAGES)):
        if not filename.endswith(".html"):
            continue
        meta, body = parse_front_matter(read(os.path.join(PAGES, filename)))
        output = meta.get("output") or filename
        canonical = canonical_for(output)

        html = render(
            base,
            {
                "title": meta.get("title", "Nishchay Photography"),
                "description": meta.get("description", ""),
                "canonical": canonical,
                "og_image": SITE_URL + meta.get("og_image", "/assets/img/og-cover.svg"),
                "og_type": meta.get("og_type", "website"),
                "body_class": meta.get("body_class", ""),
                "robots": meta.get("robots", "index, follow"),
                "jsonld": meta.get("jsonld", ""),
                "header": header,
                "footer": footer,
                "widgets": widgets,
                "content": body,
                "marker": GENERATED_MARKER,
            },
        )
        html = mark_active_nav(html, output)
        write(os.path.join(ROOT, output), html)
        outputs.append(output)
        print(f"  build  {output}")

    write(os.path.join(ROOT, "sitemap.xml"), build_sitemap(outputs))
    print("  build  sitemap.xml")
    print(f"\nBuilt {len(outputs)} pages. Preview: python3 -m http.server 8000")


if __name__ == "__main__":
    sys.exit(main())
